"""empty message

Revision ID: dc59bf955c78
Revises: b2b98fa606aa
Create Date: 2025-02-17 20:36:10.854914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc59bf955c78'
down_revision = 'b2b98fa606aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
